# Generated by Django 5.2.5 on 2025-09-08 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("webapp", "0005_alter_product_price_alter_product_product_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="profile_photo",
            field=models.ImageField(blank=True, null=True, upload_to="client_photos/"),
        ),
    ]
